import { PrismaClient } from '@prisma/client';
import { SeedContext } from './types';

export async function seedSuppliers(
  prisma: PrismaClient,
  ctx: SeedContext,
): Promise<void> {
  console.log('🏭 Seeding suppliers...');

  // ── Demo Tenant (8 suppliers) ──────────────────────────────────────
  const demoTenantId = ctx.tenants.demo.id;
  console.log('  → Demo tenant suppliers...');

  const demoSuppliers = [
    {
      tenantId: demoTenantId,
      name: 'Samsung Colombia',
      email: 'ventas@samsung.com.co',
      phone: '601-7456000',
      documentType: 'NIT' as const,
      documentNumber: '860001022-7',
      dv: '7',
      address: 'Calle 100 # 19-61, Piso 15',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Samsung Electronics Colombia S.A.',
      taxId: '860001022-7',
      notes: 'Proveedor principal de electrónicos y tecnología',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Carlos Rodríguez',
      contactPhone: '601-7456001',
    },
    {
      tenantId: demoTenantId,
      name: 'Lenovo Colombia',
      email: 'ventas@lenovo.com.co',
      phone: '601-3174500',
      documentType: 'NIT' as const,
      documentNumber: '900444555-1',
      dv: '1',
      address: 'Av. Cra 9 # 113-52, Of. 1201',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Lenovo Colombia S.A.S.',
      taxId: '900444555-1',
      notes: 'Computadores y accesorios',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'María Fernanda López',
      contactPhone: '601-3174501',
    },
    {
      tenantId: demoTenantId,
      name: 'Apple Distribución Andina',
      email: 'distribucion@apple-andina.com',
      phone: '601-5551234',
      documentType: 'NIT' as const,
      documentNumber: '900555666-2',
      dv: '2',
      address: 'Cra 11A # 93-67',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Apple Distribución Andina S.A.S.',
      taxId: '900555666-2',
      notes: 'Distribuidor autorizado Apple para la región Andina',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_60' as const,
      contactName: 'Andrés Martínez',
      contactPhone: '601-5551235',
    },
    {
      tenantId: demoTenantId,
      name: 'Sony Colombia',
      email: 'comercial@sony.com.co',
      phone: '601-6230000',
      documentType: 'NIT' as const,
      documentNumber: '860002033-8',
      dv: '8',
      address: 'Calle 93B # 12-18, Piso 4',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Sony Colombia S.A.',
      taxId: '860002033-8',
      notes: 'Audio, video y gaming',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Laura Gómez',
      contactPhone: '601-6230001',
    },
    {
      tenantId: demoTenantId,
      name: 'Arturo Calle',
      email: 'proveedores@arturocalle.com',
      phone: '601-7430000',
      documentType: 'NIT' as const,
      documentNumber: '890100100-1',
      dv: '1',
      address: 'Cra 68D # 13-10',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Arturo Calle S.A.S.',
      taxId: '890100100-1',
      notes: 'Ropa y accesorios masculinos',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_15' as const,
      contactName: 'Jorge Calle',
      contactPhone: '601-7430001',
    },
    {
      tenantId: demoTenantId,
      name: 'Nike Colombia',
      email: 'wholesale@nike.com.co',
      phone: '601-4321000',
      documentType: 'NIT' as const,
      documentNumber: '900666777-3',
      dv: '3',
      address: 'Calle 85 # 11-53, Of. 601',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Nike de Colombia S.A.',
      taxId: '900666777-3',
      notes: 'Calzado y ropa deportiva',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_60' as const,
      contactName: 'Sebastián Ruiz',
      contactPhone: '601-4321001',
    },
    {
      tenantId: demoTenantId,
      name: 'Bosch Colombia',
      email: 'ventas@bosch.com.co',
      phone: '601-8765000',
      documentType: 'NIT' as const,
      documentNumber: '860003044-9',
      dv: '9',
      address: 'Autopista Norte Km 21',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Robert Bosch Ltda.',
      taxId: '860003044-9',
      notes: 'Herramientas y electrodomésticos',
      status: 'INACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Ricardo Peña',
      contactPhone: '601-8765001',
    },
    {
      tenantId: demoTenantId,
      name: 'Proveedor Genérico',
      email: 'info@proveedorgenerico.com',
      phone: '311-2345678',
      documentType: 'CC' as const,
      documentNumber: '1234567890',
      dv: null,
      address: 'Cra 7 # 45-12',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: null,
      taxId: null,
      notes: 'Proveedor persona natural para compras varias',
      status: 'ACTIVE' as const,
      paymentTerms: 'IMMEDIATE' as const,
      contactName: 'Juan Pérez',
      contactPhone: '311-2345678',
    },
  ];

  ctx.suppliers.demo = [];
  for (const data of demoSuppliers) {
    const supplier = await prisma.supplier.create({ data });
    ctx.suppliers.demo.push(supplier);
  }
  console.log(`    ✓ ${ctx.suppliers.demo.length} demo suppliers created`);

  // ── Distribuidora Tenant (10 suppliers) ────────────────────────────
  const distribuidoraTenantId = ctx.tenants.distribuidora.id;
  console.log('  → Distribuidora tenant suppliers...');

  const distribuidoraSuppliers = [
    {
      tenantId: distribuidoraTenantId,
      name: 'Productos Familia',
      email: 'comercial@familia.com.co',
      phone: '604-3606060',
      documentType: 'NIT' as const,
      documentNumber: '890300300-1',
      dv: '1',
      address: 'Km 7 vía Medellín-Bogotá',
      city: 'Medellín',
      state: 'Antioquia',
      businessName: 'Productos Familia S.A.',
      taxId: '890300300-1',
      notes: 'Productos de aseo personal y del hogar',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Patricia Ríos',
      contactPhone: '604-3606061',
    },
    {
      tenantId: distribuidoraTenantId,
      name: 'Colgate Palmolive',
      email: 'pedidos@colgate.com.co',
      phone: '601-6511500',
      documentType: 'NIT' as const,
      documentNumber: '860004055-0',
      dv: '0',
      address: 'Calle 100 # 7-33, Torre 1',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Colgate Palmolive Cía.',
      taxId: '860004055-0',
      notes: 'Productos de cuidado personal y oral',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Diana Torres',
      contactPhone: '601-6511501',
    },
    {
      tenantId: distribuidoraTenantId,
      name: 'Bavaria S.A.',
      email: 'distribuidores@bavaria.com.co',
      phone: '601-6389000',
      documentType: 'NIT' as const,
      documentNumber: '890400400-2',
      dv: '2',
      address: 'Cra 53A # 127-35',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Bavaria S.A.',
      taxId: '890400400-2',
      notes: 'Bebidas y cervezas',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_15' as const,
      contactName: 'Alejandro Vargas',
      contactPhone: '601-6389001',
    },
    {
      tenantId: distribuidoraTenantId,
      name: 'Postobón',
      email: 'comercial@postobon.com.co',
      phone: '604-4049600',
      documentType: 'NIT' as const,
      documentNumber: '890500500-3',
      dv: '3',
      address: 'Cra 48 # 16 Sur-70',
      city: 'Medellín',
      state: 'Antioquia',
      businessName: 'Postobón S.A.',
      taxId: '890500500-3',
      notes: 'Bebidas no alcohólicas y jugos',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_15' as const,
      contactName: 'Camila Muñoz',
      contactPhone: '604-4049601',
    },
    {
      tenantId: distribuidoraTenantId,
      name: 'Colombina',
      email: 'ventas@colombina.com',
      phone: '602-4310066',
      documentType: 'NIT' as const,
      documentNumber: '890600600-4',
      dv: '4',
      address: 'Vía Cali-Yumbo Km 3',
      city: 'Cali',
      state: 'Valle del Cauca',
      businessName: 'Colombina S.A.',
      taxId: '890600600-4',
      notes: 'Confitería y snacks',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Fernando Caicedo',
      contactPhone: '602-4310067',
    },
    {
      tenantId: distribuidoraTenantId,
      name: 'Manuelita',
      email: 'comercializacion@manuelita.com',
      phone: '602-6530000',
      documentType: 'NIT' as const,
      documentNumber: '890700700-5',
      dv: '5',
      address: 'Km 7 vía Palmira-Cali',
      city: 'Palmira',
      state: 'Valle del Cauca',
      businessName: 'Manuelita S.A.',
      taxId: '890700700-5',
      notes: 'Azúcar, aceites y bioenergía',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_60' as const,
      contactName: 'Hernán Eder',
      contactPhone: '602-6530001',
    },
    {
      tenantId: distribuidoraTenantId,
      name: 'Imusa S.A.',
      email: 'mayoristas@imusa.com.co',
      phone: '604-3696969',
      documentType: 'NIT' as const,
      documentNumber: '890800800-6',
      dv: '6',
      address: 'Cra 50 # 8 Sur-117',
      city: 'Medellín',
      state: 'Antioquia',
      businessName: 'Industrias e Inversiones Imusa S.A.',
      taxId: '890800800-6',
      notes: 'Utensilios de cocina y hogar',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Luis Botero',
      contactPhone: '604-3696970',
    },
    {
      tenantId: distribuidoraTenantId,
      name: 'Harinera del Valle',
      email: 'clientes@harineradelvalle.com',
      phone: '602-8867700',
      documentType: 'NIT' as const,
      documentNumber: '890900900-7',
      dv: '7',
      address: 'Calle 5 # 36A-49',
      city: 'Cali',
      state: 'Valle del Cauca',
      businessName: 'Harinera del Valle S.A.',
      taxId: '890900900-7',
      notes: 'Harinas, pastas y productos alimenticios',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Gloria Restrepo',
      contactPhone: '602-8867701',
    },
    {
      tenantId: distribuidoraTenantId,
      name: 'Van Camps Colombia',
      email: 'pedidos@vancamps.com.co',
      phone: '601-3440055',
      documentType: 'NIT' as const,
      documentNumber: '891000100-8',
      dv: '8',
      address: 'Zona Franca Bogotá, Bod. 12',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Van Camps S.A.S.',
      taxId: '891000100-8',
      notes: 'Atún y conservas de pescado',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_15' as const,
      contactName: 'Andrea Mejía',
      contactPhone: '601-3440056',
    },
    {
      tenantId: distribuidoraTenantId,
      name: 'Darnel',
      email: 'ventas@darnel.com',
      phone: '601-5461111',
      documentType: 'NIT' as const,
      documentNumber: '891100200-9',
      dv: '9',
      address: 'Cra 106 # 15A-25, Zona Industrial',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Darnel Group S.A.S.',
      taxId: '891100200-9',
      notes: 'Empaques y desechables',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Roberto Darnalt',
      contactPhone: '601-5461112',
    },
  ];

  ctx.suppliers.distribuidora = [];
  for (const data of distribuidoraSuppliers) {
    const supplier = await prisma.supplier.create({ data });
    ctx.suppliers.distribuidora.push(supplier);
  }
  console.log(
    `    ✓ ${ctx.suppliers.distribuidora.length} distribuidora suppliers created`,
  );

  // ── Nuevo Negocio Tenant (2 suppliers) ─────────────────────────────
  const nuevoTenantId = ctx.tenants.nuevo.id;
  console.log('  → Nuevo Negocio tenant suppliers...');

  const nuevoSuppliers = [
    {
      tenantId: nuevoTenantId,
      name: 'Confecciones Medellín',
      email: 'ventas@confeccionesmedellin.com',
      phone: '604-2223344',
      documentType: 'NIT' as const,
      documentNumber: '901200300-1',
      dv: '1',
      address: 'Calle 52 # 46-75',
      city: 'Medellín',
      state: 'Antioquia',
      businessName: 'Confecciones Medellín S.A.S.',
      taxId: '901200300-1',
      notes: 'Confecciones y ropa al por mayor',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Natalia Rendón',
      contactPhone: '604-2223345',
    },
    {
      tenantId: nuevoTenantId,
      name: 'Textiles del Valle',
      email: 'comercial@textilesdelvalle.com',
      phone: '602-5556677',
      documentType: 'NIT' as const,
      documentNumber: '901300400-2',
      dv: '2',
      address: 'Cra 1 # 28-56, Zona Industrial',
      city: 'Cali',
      state: 'Valle del Cauca',
      businessName: 'Textiles del Valle S.A.',
      taxId: '901300400-2',
      notes: 'Telas y textiles al por mayor',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Oscar Valencia',
      contactPhone: '602-5556678',
    },
  ];

  ctx.suppliers.nuevo = [];
  for (const data of nuevoSuppliers) {
    const supplier = await prisma.supplier.create({ data });
    ctx.suppliers.nuevo.push(supplier);
  }
  console.log(
    `    ✓ ${ctx.suppliers.nuevo.length} nuevo negocio suppliers created`,
  );

  // ── Papelería Tenant (5 suppliers) ─────────────────────────────────
  const papeleriaTenantId = ctx.tenants.papeleria.id;
  console.log('  → Papelería tenant suppliers...');

  const papeleriaSuppliers = [
    {
      tenantId: papeleriaTenantId,
      name: 'Carvajal Educación',
      email: 'institucional@carvajaleducacion.com',
      phone: '602-8824800',
      documentType: 'NIT' as const,
      documentNumber: '890200200-0',
      dv: '0',
      address: 'Calle 29N # 6A-40',
      city: 'Cali',
      state: 'Valle del Cauca',
      businessName: 'Carvajal Educación S.A.S.',
      taxId: '890200200-0',
      notes: 'Cuadernos, libros y material educativo',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Juliana Carvajal',
      contactPhone: '602-8824801',
    },
    {
      tenantId: papeleriaTenantId,
      name: 'Faber-Castell Colombia',
      email: 'ventas@faber-castell.com.co',
      phone: '601-5432100',
      documentType: 'NIT' as const,
      documentNumber: '891400500-3',
      dv: '3',
      address: 'Cra 7 # 71-52, Torre B',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'A.W. Faber-Castell Colombia S.A.S.',
      taxId: '891400500-3',
      notes: 'Lápices, colores y artículos de escritura',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Esteban Krause',
      contactPhone: '601-5432101',
    },
    {
      tenantId: papeleriaTenantId,
      name: 'Totto S.A.',
      email: 'mayoristas@totto.com',
      phone: '601-7459000',
      documentType: 'NIT' as const,
      documentNumber: '891500600-4',
      dv: '4',
      address: 'Cra 68D # 13-10',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Nalsani S.A.S. (Totto)',
      taxId: '891500600-4',
      notes: 'Maletas, morrales y accesorios escolares',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_15' as const,
      contactName: 'Yonatan Bursztyn',
      contactPhone: '601-7459001',
    },
    {
      tenantId: papeleriaTenantId,
      name: '3M Colombia',
      email: 'oficina@3m.com.co',
      phone: '601-4501200',
      documentType: 'NIT' as const,
      documentNumber: '860005066-1',
      dv: '1',
      address: 'Calle 100 # 19-54, Piso 7',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: '3M Colombia S.A.',
      taxId: '860005066-1',
      notes: 'Post-it, cintas y artículos de oficina',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_60' as const,
      contactName: 'Daniela Pardo',
      contactPhone: '601-4501201',
    },
    {
      tenantId: papeleriaTenantId,
      name: 'Pelikan Colombia',
      email: 'distribuidores@pelikan.com.co',
      phone: '601-3219800',
      documentType: 'NIT' as const,
      documentNumber: '891600700-5',
      dv: '5',
      address: 'Av. Dorado # 68C-61',
      city: 'Bogotá',
      state: 'Cundinamarca',
      businessName: 'Pelikan Colombia Ltda.',
      taxId: '891600700-5',
      notes: 'Tintas, pegantes y artículos escolares',
      status: 'ACTIVE' as const,
      paymentTerms: 'NET_30' as const,
      contactName: 'Marcos Pelikan',
      contactPhone: '601-3219801',
    },
  ];

  ctx.suppliers.papeleria = [];
  for (const data of papeleriaSuppliers) {
    const supplier = await prisma.supplier.create({ data });
    ctx.suppliers.papeleria.push(supplier);
  }
  console.log(
    `    ✓ ${ctx.suppliers.papeleria.length} papelería suppliers created`,
  );

  console.log(
    `✅ Suppliers seeded: ${ctx.suppliers.demo.length + ctx.suppliers.distribuidora.length + ctx.suppliers.nuevo.length + ctx.suppliers.papeleria.length} total`,
  );
}
